### ISSUE TITLE
Server password shouldn't be mandatory

### ISSUE THREAD

**Issue by foxycode** [automatephp/automate#62]
Error:
```bash
Fatal error: Uncaught TypeError: Automate\VariableResolver::isVariable(): Argument #1 ($value) must be of type string, null given, called in phar:///usr/local/bin/automate/src/Automate/VariableResolver.php on line 36 and defined in phar:///usr/local/bin/automate/src/Automate/VariableResolver.php:61
Stack trace:
#0 phar:///usr/local/bin/automate/src/Automate/VariableResolver.php(36): Automate\VariableResolver->isVariable(NULL)
#1 phar:///usr/local/bin/automate/src/Automate/Command/DeployCommand.php(51): Automate\VariableResolver->process(Object(Automate\Model\Platform))
#2 phar:///usr/local/bin/automate/vendor/symfony/console/Command/Command.php(279): Automate\Command\DeployCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 phar:///usr/local/bin/automate/vendor/symfony/console/Application.php(1031): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 phar:///usr/local/bin/automate/vendor/symfony/console/Application.php(318): Symfony\Component\Console\Application->doRunCommand(Object(Automate\Command\DeployCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 phar:///usr/local/bin/automate/vendor/symfony/console/Application.php(169): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 phar:///usr/local/bin/automate/bin/automate(19): Symfony\Component\Console\Application->run()
#7 /usr/local/bin/automate(15): require('phar:///usr/loc...')
#8 {main}
  thrown in phar:///usr/local/bin/automate/src/Automate/VariableResolver.php on line 61
```

Works fine if I provide **any** server password in config. I am using keys, so password shouldn't be mandatory as it was in previous versions.

**Comment by julienj** [comment]
Can you test it with version 4.0.1?
